# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/cfg/clocks.xdc

# XDC: imports/cfg/ports.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ds_buf_1_0 || ORIG_REF_NAME==system_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_2_0/system_util_ds_buf_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ds_buf_2_0 || ORIG_REF_NAME==system_util_ds_buf_2_0} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_125M_0 || ORIG_REF_NAME==system_rst_ps7_0_125M_0} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_imp_xbar_0/system_ps7_0_axi_periph_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_imp_xbar_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_imp_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_0/system_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_125M_1/system_rst_ps7_0_125M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_125M_1 || ORIG_REF_NAME==system_rst_ps7_0_125M_1} -quiet] -quiet

# IP: bd/system/ip/system_axis_red_pitaya_adc_0_0/system_axis_red_pitaya_adc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_adc_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_adc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_0/system_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlslice_0_0 || ORIG_REF_NAME==system_xlslice_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_1_1/system_xlconstant_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconstant_1_1 || ORIG_REF_NAME==system_xlconstant_1_1} -quiet] -quiet

# IP: bd/system/ip/system_c_addsub_0_0/system_c_addsub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_c_addsub_0_0 || ORIG_REF_NAME==system_c_addsub_0_0} -quiet] -quiet

# IP: bd/system/ip/system_mult_gen_0_1/system_mult_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_mult_gen_0_1 || ORIG_REF_NAME==system_mult_gen_0_1} -quiet] -quiet

# IP: bd/system/ip/system_mult_gen_0_2/system_mult_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_mult_gen_0_2 || ORIG_REF_NAME==system_mult_gen_0_2} -quiet] -quiet

# IP: bd/system/ip/system_xfft_0_0/system_xfft_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xfft_0_0 || ORIG_REF_NAME==system_xfft_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_1/system_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconcat_0_1 || ORIG_REF_NAME==system_xlconcat_0_1} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_1_0/system_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlslice_1_0 || ORIG_REF_NAME==system_xlslice_1_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_1_1/system_xlslice_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlslice_1_1 || ORIG_REF_NAME==system_xlslice_1_1} -quiet] -quiet

# IP: bd/system/ip/system_Mag_valid_0_0/system_Mag_valid_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Mag_valid_0_0 || ORIG_REF_NAME==system_Mag_valid_0_0} -quiet] -quiet

# IP: bd/system/ip/system_Counter_enable_fft_0_0/system_Counter_enable_fft_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Counter_enable_fft_0_0 || ORIG_REF_NAME==system_Counter_enable_fft_0_0} -quiet] -quiet

# IP: bd/system/ip/system_counter_buffer_fft_0_0/system_counter_buffer_fft_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_counter_buffer_fft_0_0 || ORIG_REF_NAME==system_counter_buffer_fft_0_0} -quiet] -quiet

# IP: bd/system/ip/system_c_counter_binary_1_0/system_c_counter_binary_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_c_counter_binary_1_0 || ORIG_REF_NAME==system_c_counter_binary_1_0} -quiet] -quiet

# IP: bd/system/ip/system_Mag_delay_0_0/system_Mag_delay_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Mag_delay_0_0 || ORIG_REF_NAME==system_Mag_delay_0_0} -quiet] -quiet

# IP: bd/system/ip/system_c_addsub_0_1/system_c_addsub_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_c_addsub_0_1 || ORIG_REF_NAME==system_c_addsub_0_1} -quiet] -quiet

# IP: bd/system/ip/system_c_counter_binary_0_2/system_c_counter_binary_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_c_counter_binary_0_2 || ORIG_REF_NAME==system_c_counter_binary_0_2} -quiet] -quiet

# IP: bd/system/ip/system_blk_mem_gen_0_2/system_blk_mem_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_blk_mem_gen_0_2 || ORIG_REF_NAME==system_blk_mem_gen_0_2} -quiet] -quiet

# IP: bd/system/ip/system_c_counter_binary_1_1/system_c_counter_binary_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_c_counter_binary_1_1 || ORIG_REF_NAME==system_c_counter_binary_1_1} -quiet] -quiet

# IP: bd/system/ip/system_CE_delay_0_0/system_CE_delay_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_CE_delay_0_0 || ORIG_REF_NAME==system_CE_delay_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ACC_0_0/system_ACC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ACC_0_0 || ORIG_REF_NAME==system_ACC_0_0} -quiet] -quiet

# IP: bd/system/ip/system_MUX_0_0/system_MUX_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_MUX_0_0 || ORIG_REF_NAME==system_MUX_0_0} -quiet] -quiet

# IP: bd/system/ip/system_c_counter_binary_2_0/system_c_counter_binary_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_c_counter_binary_2_0 || ORIG_REF_NAME==system_c_counter_binary_2_0} -quiet] -quiet

# IP: bd/system/ip/system_Counter_control_acc_0_0/system_Counter_control_acc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Counter_control_acc_0_0 || ORIG_REF_NAME==system_Counter_control_acc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_blk_mem_gen_1_1/system_blk_mem_gen_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_blk_mem_gen_1_1 || ORIG_REF_NAME==system_blk_mem_gen_1_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_bram_ctrl_0_1/system_axi_bram_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_bram_ctrl_0_1 || ORIG_REF_NAME==system_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_imp_auto_pc_1/system_ps7_0_axi_periph_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_imp_auto_pc_1 || ORIG_REF_NAME==system_ps7_0_axi_periph_imp_auto_pc_1} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_imp_auto_us_0/system_ps7_0_axi_periph_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_imp_auto_us_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_imp_auto_us_0} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_imp_auto_ds_0/system_ps7_0_axi_periph_imp_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_imp_auto_ds_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_imp_auto_ds_0} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_imp_auto_pc_0/system_ps7_0_axi_periph_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_imp_auto_pc_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_imp_auto_pc_0} -quiet] -quiet

# XDC: /home/nehaal-raj/vivado_projects/Digital_correlator/adc_characterization_fin/adc_characterization_fin.gen/sources_1/bd/system/system_ooc.xdc
